# Generated by Django 4.1.7 on 2023-03-21 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('TE', 'Teacher'), ('ST', 'Student')], default='ST', max_length=2),
        ),
    ]
