# Generated by Django 4.1.7 on 2023-03-11 06:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0003_rename_course_teacher_courses_student_assignment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='assignment',
            name='allow_submit',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='assignment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='assignment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
