# Generated by Django 4.1.7 on 2023-03-21 00:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0010_remove_teacher_first_name_remove_teacher_last_name_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Member',
        ),
    ]
