# Generated by Django 4.1.7 on 2023-03-21 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0012_userrole'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserRole',
        ),
    ]
