# Generated by Django 4.1.7 on 2023-03-23 06:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0013_delete_userrole'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='teachers',
        ),
        migrations.AddField(
            model_name='assignment',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignments', to='playground.teacher'),
        ),
    ]
