# Generated by Django 4.1.7 on 2023-03-25 07:50

import django.core.validators
from django.db import migrations, models
import playground.validators


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0022_alter_lesson_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='course/videos', validators=[playground.validators.FileSizeValidator(max_mb=3), django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'webm', 'ogg'])]),
        ),
    ]
