# Generated by Django 4.1.7 on 2023-03-25 17:16

import django.core.validators
from django.db import migrations, models
import playground.validators


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0026_alter_student_profile_picture_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='profile_picture',
            field=models.ImageField(default=None, null=True, upload_to='student/images', validators=[playground.validators.FileSizeValidator(max_mb=5), django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'png', 'webp'])]),
        ),
    ]
