# Generated by Django 4.1.7 on 2023-03-26 03:28

import django.core.validators
from django.db import migrations, models
import playground.validators


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0028_assignment_description_assignmentmaterial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignmentmaterial',
            name='file',
            field=models.FileField(upload_to='assignment', validators=[playground.validators.FileSizeValidator(max_mb=5), django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'png', 'webp', 'zip', 'pdf', 'txt', 'docx', 'xlsx', 'pptx'])]),
        ),
        migrations.AlterField(
            model_name='student',
            name='profile_picture',
            field=models.ImageField(default=None, null=True, upload_to='student/images', validators=[playground.validators.FileSizeValidator(max_mb=1), django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'png', 'webp'])]),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='profile_picture',
            field=models.ImageField(default=None, null=True, upload_to='teacher/images', validators=[playground.validators.FileSizeValidator(max_mb=1), django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'png', 'webp'])]),
        ),
    ]
