# Generated by Django 4.1.7 on 2023-03-26 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0029_alter_assignmentmaterial_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
