# Generated by Django 4.1.7 on 2023-03-26 10:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0031_lesson_teacher'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherJoinCourseRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_join_course_requests', to='playground.course')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_join_course_requests', to='playground.teacher')),
            ],
        ),
    ]
